version: '3'

services:
  nginx:
    image: nginx
    volumes:
        - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
        - front
        - backend
  php:
    build: 
        context: ./config/php
    volumes: 
      - ./:/var/www
    ports:
      - 80:80
    networks:
      - backend

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - 3306:3306
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    networks:
      - backend

networks:
  front:
      external:
          name: front
  backend: