version: '3'

services:
  nginx:
    image: nginx
    volumes:
        - ./config/nginx/:/etc/nginx/conf.d/
    networks:
        - front
        - backend
    ports:
      - 80:80
  php:
    build: 
        context: ./config/php
    volumes: 
      - ./:/var/www
    networks:
      - backend

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - backend

networks:
  front:
      external:
          name: front
  backend: